### ISSUE TITLE
[feature] Search action webhook payload for required keys (branch/ref, pr number)

### ISSUE THREAD

**Issue by covertbert** [percy/storybook-action#13]
I [submitted a PR](https://github.com/percy/storybook-action/pull/12) to you guys the other with a suggestion on how the action might be fixed to accommodate workflow runs that are triggered by the `pull_request_review` event. Apologies for not making it clear but I didn't intend for it to be merged without testing as I hadn't tested it myself!

Anyway, the action is now broken on the latest release and won't work for the `pull_request` event either. Do you guys have the bandwidth to take a proper look at this and fix it?

**Comment by Robdel12** [comment]
This should be "fixed" with v0.1.5. The issue wasn't setting the PR number in this workflow trigger, the issue is the branch ref is in a different place (which caused the 💥 on replace of a undefined string). 

I'll hopefully have a follow up PR that makes it easy to search the entire webhook payload for the info we need. It's clear no payload matches the same shape, so we're going to constantly play this game.

**Comment by covertbert** [comment]
Awesome, thanks for dealing with this so quickly!
